//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final2.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proyecto_Final2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categor.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The keys with which the message was signed are:.
        /// </summary>
        public static string ClavesMensaje {
            get {
                return ResourceManager.GetString("ClavesMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send message.
        /// </summary>
        public static string EnviarCadena {
            get {
                return ResourceManager.GetString("EnviarCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The signature of the entered message is:.
        /// </summary>
        public static string FirmaMensaje {
            get {
                return ResourceManager.GetString("FirmaMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Hash.
        /// </summary>
        public static string Hash_del_archivo {
            get {
                return ResourceManager.GetString("Hash del archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The hash of the following image is:.
        /// </summary>
        public static string HashImagen {
            get {
                return ResourceManager.GetString("HashImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The asymmetrically encrypted message is:.
        /// </summary>
        public static string MensajeCifradoAsimetrico {
            get {
                return ResourceManager.GetString("MensajeCifradoAsimetrico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Symmetrically encrypted message:.
        /// </summary>
        public static string MensajeCifradoSimetrico {
            get {
                return ResourceManager.GetString("MensajeCifradoSimetrico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message decrypted asymmetrically:.
        /// </summary>
        public static string MensajeDescifradoAsimetrico {
            get {
                return ResourceManager.GetString("MensajeDescifradoAsimetrico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message decrypted symmetrically:.
        /// </summary>
        public static string MensajeDescifradoSimetrico {
            get {
                return ResourceManager.GetString("MensajeDescifradoSimetrico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product name.
        /// </summary>
        public static string NombreProducto {
            get {
                return ResourceManager.GetString("NombreProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello World!.
        /// </summary>
        public static string Saludo {
            get {
                return ResourceManager.GetString("Saludo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data access service.
        /// </summary>
        public static string Servicio_de_acceso_a_datos {
            get {
                return ResourceManager.GetString("Servicio de acceso a datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data encryption service.
        /// </summary>
        public static string Servicio_de_cifrado_de_datos {
            get {
                return ResourceManager.GetString("Servicio de cifrado de datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digital signature service.
        /// </summary>
        public static string Servicio_firma_digital {
            get {
                return ResourceManager.GetString("Servicio firma digital", resourceCulture);
            }
        }
    }
}
